name: Adding a Pick
description: Add a pick from the back catalog to the Pick Pen (Before LUP 600). This is for adding picks that the show has chosen. Please do not add your personal picks.
labels:
  - "pick"
body:
  - id: title
    type: input
    attributes:
      label: Name
      description: This should match the title in the episode's show notes.
      placeholder: Pick Name
    validations:
      required: true
  - id: url
    type: input
    attributes:
      label: Pick URL
      description: This should match the link in the episode's show notes.
    validations:
      required: true
  - id: description
    type: textarea
    attributes:
      label: Description
      description: This should match the description in the episode's show notes.
    validations:
      required: true 
  - id: license
    type: input
    attributes:
      label: License
      description: What is the license of the pick?
      placeholder: AGPL-3.0
  - id: shows
    type: dropdown
    attributes:
      label: Show
      multiple: true
      default: 0
      options:
        - LINUX Unplugged
        - This Week in Bitcoin
        - The Launch
        - Jupiter Extras
        - Coder Radio
        - Linux Action News
        - Office Hours
        - Self-Hosted
    validations:
      required: true
  - id: episode
    type: input
    attributes:
      label: Episode Number
      placeholder: '600'
    validations:
      required: true
